import { Tag } from 'antd';

import type { AppointmentBriefRecord } from '../../lib/api';
import { compactStringArray, formatDateTime } from './formatters';

function decodeEscapedUnicode(value: string) {
  return value.replace(/\\u([0-9a-fA-F]{4})/g, (_, hex: string) =>
    String.fromCharCode(Number.parseInt(hex, 16)),
  );
}

export function cleanBriefText(value: string) {
  return decodeEscapedUnicode(value)
    .replace(/\u2014/g, ' - ')
    .replace(/\s+/g, ' ')
    .trim();
}

export function getCustomerName(brief: AppointmentBriefRecord): string {
  const { firstName, lastName, email } = brief.booking.customer;
  const fullName = [firstName, lastName].filter(Boolean).join(' ').trim();

  return fullName || email;
}

export function getBriefBarberName(brief: AppointmentBriefRecord): string {
  return (
    brief.barber?.displayName ??
    brief.booking.staff?.displayName ??
    'Unassigned'
  );
}

export function getBriefSafetyLines(brief: AppointmentBriefRecord): string[] {
  return (brief.safetyNotes ?? '')
    .split('\n')
    .map(cleanBriefText)
    .filter(Boolean);
}

function formatBriefLabel(value: string): string {
  return value
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

export function getBriefSummaryLines(brief: AppointmentBriefRecord): string[] {
  return cleanBriefText(brief.clientSummary)
    .split(/\s+\|\s+|(?<=\.)\s+(?=[A-Z][a-z]+(?:\s+[a-z]+)?:)/)
    .map((line) =>
      line.replace(/^([a-z][a-z0-9-]*):/i, (_, label: string) => {
        return `${formatBriefLabel(label)}:`;
      }),
    )
    .map((line) => line.trim())
    .filter(Boolean);
}

export function buildPrepBriefText(brief: AppointmentBriefRecord): string {
  const safetyLines = getBriefSafetyLines(brief);
  const summaryLines = getBriefSummaryLines(brief);
  const generationText =
    brief.generationSource === 'claude'
      ? `Claude${brief.generationModel ? ` (${brief.generationModel})` : ''}`
      : 'Deterministic fallback';

  return [
    `Customer: ${getCustomerName(brief)}`,
    `Service: ${brief.booking.service.name}`,
    `Appointment: ${formatDateTime(brief.booking.startAt)}`,
    `Barber: ${getBriefBarberName(brief)}`,
    `Generated by: ${generationText}`,
    '',
    'Client summary:',
    summaryLines.length > 0
      ? summaryLines.map((line) => `- ${line}`).join('\n')
      : 'Not recorded',
    '',
    'Hair state:',
    compactStringArray(brief.hairState).map(cleanBriefText).join(', ') ||
      'None recorded',
    '',
    'Desired look:',
    brief.desiredLook ? cleanBriefText(brief.desiredLook) : 'Not provided',
    '',
    'Safety notes:',
    safetyLines.length > 0 ? safetyLines.join('\n') : 'No safety notes',
  ].join('\n');
}

export function renderBriefGenerationTag(brief: AppointmentBriefRecord) {
  if (brief.generationSource === 'claude') {
    return <Tag color="green">{brief.generationModel ?? 'Claude'}</Tag>;
  }

  return <Tag color="gold">Fallback</Tag>;
}

export function getBriefGoalPhotoSrc(
  brief: AppointmentBriefRecord,
): string | null {
  if (!brief.goalPhoto) {
    return null;
  }

  return `data:${brief.goalPhoto.mediaType};base64,${brief.goalPhoto.data}`;
}
