export const REDIS_CLUSTER = {
  PRIMARY: 'REDIS_PRIMARY',
  READER: 'REDIS_READER',
} as const;

export const REDIS_CACHE_ENABLED_ENV = 'REDIS_CACHE_ENABLED';

export const REDIS_CACHE_DEFAULT_TTL_SECONDS_ENV =
  'REDIS_CACHE_DEFAULT_TTL_SECONDS';
